name: Deploy my Lambda Function

# trigger on all push events to main branch
on: 
  push:
    branches:
      - feature*

jobs:

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up NodeJS
        uses: actions/setup-node@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Run NPM
        run: |
            npm ci
            npm test
            npm install gatsby-plugin-s3
            npm run deploy

